version: '2'
services:
  eureka-server:
    ports:
    - "9001:9001"
  front-gateway:
    build: front-gateway/.
    ports:
      - "9999:9999"
    links:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9001/eureka

  push-service:
    build: push-service/.
    ports:
      - "9991:9991"
    links:
      - eureka-server
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9001/eureka
  upload-service:
    build: upload-service/.
    ports:
      - "9995:9995"
    links:
      - eureka-server
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:9001/eureka
