version: '2.1'
services:

  eureka-server:
    ports:
    - "9001:9001"
    build: eureka-server/.
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 10s
      timeout: 30s
      retries: 10

  front-gateway:
    build: front-gateway/.
    ports:
      - "9999:9999"
    links:
      - eureka-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999" ]
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      eureka-server:
        condition: service_healthy


  push-service:
    build: push-service/.
    ports:
      - "9991:9991"
    links:
      - eureka-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9991" ]
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      eureka-server:
        condition: service_healthy


  upload-service:
    build: upload-service/.
    ports:
      - "9995:9995"
    links:
      - eureka-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9995" ]
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      eureka-server:
        condition: service_healthy

  api-gateway:
    build: api-gateway/.
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - "9100:9100"
    links:
      - eureka-server