version: '2'
services:
  front-gateway:
    build: front-gateway/.
    ports:
      - "9999:9999"
  push-service:
    build: push-service/.
    ports:
      - "9991:9991"
  upload-service:
    build: upload-service/.
    ports:
      - "9995:9995"
