server:
  servlet:
    context-path: /front-gateway
  port: 9999

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${pg.url}
    username: ${pg.user}
    password: ${pg.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  application:
    name: front-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://109.248.203.238:9001/eureka/
  instance:
    prefer-ip-address: true