server:
  port: 9995
  servlet:
    context-path: /upload-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${pg.url}
    username: ${pg.user}
    password: ${pg.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  application:
    name: upload-service
  cloud:
    discovery:
      enabled: true

bucket:
  name: ${secret.bucket.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${host}:${eureka.port}/eureka/
  instance:
    prefer-ip-address: true