server:
  port: 9995
  servlet:
    context-path: /upload_service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${pg.url}
    username: ${pg.user}
    password: ${pg.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  application:
    name: upload-service

bucket:
  name: ${secret.bucket.name}