spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      enabled: true

server:
  port: 9001

eureka:
  instance:
    hostname: ${host}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


