spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      enabled: true

server:
  port: 9001

eureka:
  instance:
    hostname: ${host}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


